language: java
script:
  - |
    echo "Will running plugin-test"
    asdf plugin-test kotlin https://github.com/missingcharacter/asdf-kotlin.git
    echo "Adding kotlin and java via 'asdf plugin-add'"
    asdf plugin-add kotlin
    asdf plugin-add java
    echo "Will try to install java's openjdk-11.0.1"
    asdf install java openjdk-11.0.1
    echo "Trying to list all versions of kotlin"
    asdf list-all kotlin
    echo "Will add 'java openjdk-11.0.1' to "
    echo "java openjdk-11.0.1" > ~/.tool-versions
    echo "Will try to install kotlin 1.0.3 (version without kotlin native)"
    asdf install kotlin 1.0.3
    echo "Will try to install kotlin 1.3.21 (version with kotlin native)"
    asdf install kotlin 1.3.21
    echo "Setting kotlin 1.0.3 as the default value in ~/.tool-versions"
    echo 'kotlin 1.0.3' >> ~/.tool-versions
    echo "Confirming version 1.0.3"
    kotlin -version | grep '1.0.3'
    echo "Confirming version 1.3.21"
    echo "java openjdk-11.0.1" > ~/.tool-versions
    echo 'kotlin 1.3.21' >> ~/.tool-versions
    kotlin -version | grep '1.3.21'
    kotlinc-native -version | grep '1.3.21'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
